-- DEVELOPER: ANASWARA
-- DESCRIPTION: T-SQL SCRIPT WHICH CREATES THE FOLLOWING OBJECTS:
-- DATABASE
-- TABLE

-- TO DELETE A DB, YOU NEED TO BE ON ANOTHER DB
PRINT 'USING MASTER DB...'
USE MASTER;
GO

-- DELETE THE MITRADB DATABASE IF IT EXISTS  
PRINT 'CHECKING IF MITRADBDB EXISTS...'
IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='MITRADBDB')
	-- DELETE DATABASE ANADERIDB
BEGIN
	PRINT 'MITRADB EXISTS AND WILL BE DELETED...'
	DROP DATABASE MITRADB;
END;

-- CREATE A NEW DATABASE TEMPDEVDB
BEGIN
	PRINT 'MITRADBDB DOES NOT EXISTS AND WILL BE CREATED...'
	CREATE DATABASE MITRADB;
END;
GO

-- USE THE NEWLY CREATED DB
USE MITRADB;
PRINT 'USING MITRADB DB...'
GO